// from https://github.com/paul1956/CareLink/blob/238c48a3ad0d51cf02497d6820f55870ddbc01c5/src/CareLink/Extensions/CountryCodes.vb#L15

import logger from "./logger.js";

const countryCodeToName: Record<string, string> = {
  US: "United States",
  AL: "Albania",
  DZ: "Algeria",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BM: "Bermuda",
  BO: "Bolivia",
  BA: "Bosnia-Herzegovina",
  BW: "Botswana",
  BR: "Brazil",
  BG: "Bulgaria",
  CA: "Canada",
  CL: "Chile",
  CO: "Colombia",
  CR: "Costa Rica",
  HR: "Croatia",
  CW: "Curacao",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  EE: "Estonia",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GE: "Georgia",
  DE: "Germany",
  GB: "Great Britain",
  GR: "Greece",
  GT: "Guatemala",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  XK: "Kosovo",
  KW: "Kuwait",
  LV: "Latvia",
  LB: "Lebanon",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macau",
  MK: "Macedonia",
  MY: "Malaysia",
  MV: "Maldives",
  MT: "Malta",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  MD: "Moldova",
  ME: "Montenegro",
  MA: "Morocco",
  NA: "Namibia",
  NL: "Netherlands",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PA: "Panama",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  QA: "Qatar",
  RO: "Romania",
  RU: "Russia",
  SA: "Saudi Arabia",
  RS: "Serbia",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  ZA: "South Africa",
  KR: "South Korea",
  ES: "Spain",
  SD: "Sudan",
  SE: "Sweden",
  CH: "Switzerland",
  TW: "Taiwan",
  TH: "Thailand",
  TT: "Trinidad & Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  UK: "United Kingdom",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VE: "Venezuela",
  VN: "Vietnam",
};

const countryToRegion: Record<string, string> = {
  "United States": "North America",
  Albania: "Europe",
  Algeria: "Africa",
  Argentina: "South America",
  Armenia: "Asia",
  Aruba: "South America",
  Australia: "Oceania",
  Austria: "Europe",
  Azerbaijan: "Asia",
  Bahamas: "North America",
  Bahrain: "Asia",
  Bangladesh: "Asia",
  Barbados: "North America",
  Belarus: "Europe",
  Belgium: "Europe",
  Bermuda: "North America",
  Bolivia: "South America",
  "Bosnia-Herzegovina": "Europe",
  Botswana: "Africa",
  Brazil: "South America",
  Bulgaria: "Europe",
  Canada: "North America",
  Chile: "South America",
  Colombia: "South America",
  "Costa Rica": "North America",
  Croatia: "Europe",
  Curacao: "South America",
  Cyprus: "Europe",
  "Czech Republic": "Europe",
  Denmark: "Europe",
  "Dominican Republic": "North America",
  Ecuador: "South America",
  Egypt: "Africa",
  "El Salvador": "North America",
  Estonia: "Europe",
  Fiji: "Oceania",
  Finland: "Europe",
  France: "Europe",
  Georgia: "Europe",
  Germany: "Europe",
  "Great Britain": "GB",
  Greece: "Europe",
  Guatemala: "North America",
  Honduras: "North America",
  "Hong Kong": "Asia",
  Hungary: "Europe",
  Iceland: "Europe",
  India: "Asia",
  Indonesia: "Asia",
  Iraq: "Asia",
  Ireland: "Europe",
  Israel: "Asia",
  Italy: "Europe",
  Jamaica: "North America",
  Japan: "Asia",
  Jordan: "Asia",
  Kazakhstan: "Asia",
  Kenya: "Africa",
  Kosovo: "Europe",
  Kuwait: "Asia",
  Latvia: "Europe",
  Lebanon: "Asia",
  Libya: "Africa",
  Liechtenstein: "Europe",
  Lithuania: "Europe",
  Luxembourg: "Europe",
  Macau: "Asia",
  Malaysia: "Asia",
  Maldives: "Asia",
  Malta: "Europe",
  Macedonia: "Europe",
  Mauritius: "Africa",
  Mayotte: "Africa",
  Mexico: "North America",
  Moldova: "Europe",
  Montenegro: "Europe",
  Morocco: "Africa",
  Namibia: "Africa",
  Netherlands: "Europe",
  "New Caledonia": "Oceania",
  "New Zealand": "Oceania",
  Nicaragua: "North America",
  Norway: "Europe",
  Oman: "Asia",
  Pakistan: "Asia",
  Panama: "North America",
  Paraguay: "South America",
  Peru: "South America",
  Philippines: "Asia",
  Poland: "Europe",
  Portugal: "Europe",
  "Puerto Rico": "North America",
  Qatar: "Asia",
  Romania: "Europe",
  Russia: "Europe",
  "Saudi Arabia": "Asia",
  Serbia: "Europe",
  Singapore: "Asia",
  Slovakia: "Europe",
  Slovenia: "Europe",
  "South Africa": "Africa",
  "South Korea": "Asia",
  Spain: "Europe",
  Sudan: "Africa",
  Sweden: "Europe",
  Switzerland: "Europe",
  Taiwan: "Asia",
  Thailand: "Asia",
  "Trinidad & Tobago": "South America",
  Tunisia: "Africa",
  Turkey: "Asia",
  Ukraine: "Europe",
  "United Arab Emirates": "Asia",
  "United Kingdom": "Europe",
  Uruguay: "South America",
  Uzbekistan: "Asia",
  Venezuela: "South America",
  Vietnam: "Asia",
};

const regions = [
  "North America",
  "Africa",
  "Asia",
  "Europe",
  "Oceania",
  "South America",
];

const urlsByRegion: Record<string, string> = {
  "North America": "CareLink.MiniMed.com",
  Europe: "CareLink.MiniMed.eu",
  default: "CareLink.MiniMed.eu",
};

export function getRegionFromCountryCode(countryCode: string) {
  let country = countryCodeToName[countryCode.toUpperCase()];
  if (!country) {
    logger.warn(
      {
        countryCode,
      },
      "no countryCode found for %s",
      countryCode
    );
    country = countryCodeToName["AR"]; // defaults to AR
  }
  const region = countryToRegion[country];
  return region ?? regions.at(-1);
}

export function getCarelinkUrl(countryCode: string) {
  const url = urlsByRegion[getRegionFromCountryCode(countryCode)];
  return url ?? urlsByRegion.default;
}
